In [8]:
import numpy as np

Create a vector with values ranging from 10 to 49.

In [111]:
vector=np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Create a 3x3 matrix with values ranging from 0 to 8.


In [14]:
matrix=np.array(np.arange(0,9).reshape(3,3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3x3 identity matrix.


In [17]:
id_matrix=np.eye(3,3,dtype=int)
id_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Create a 3x3x3 array with random values.


In [22]:
arr=np.array(np.random.randn(3,3,3))
arr


array([[[-1.17617219, -2.0538075 , -0.94766111],
        [-0.90353546,  0.82259978,  0.13487513],
        [ 0.6811906 ,  0.55139791,  1.27676885]],

       [[-0.64615907, -0.16466021,  1.12908096],
        [ 1.60749406,  1.4594745 , -0.16661357],
        [ 1.68668062, -0.31802526, -0.56031584]],

       [[ 0.00237695, -1.89543648,  1.13902114],
        [-0.33908033,  0.52547399,  0.15706299],
        [-1.14706406, -0.0242247 ,  0.75025513]]])

Create a 10x10 array with random values and find the minimum and maximum values.


In [38]:
arr1=np.array(np.random.randint(-50,100,(3,3)))
print(arr1)

max_arr=arr1.max()
print(max_arr)

min_arr=arr1.min()
print(min_arr)

[[ 75  55  99]
 [-38 -43  63]
 [ 10  32  73]]
99
-43


Create a random vector of size 30 and find the mean value.


In [44]:
vector=np.random.randint(0,100,30)
print(vector)

mean_val=vector.mean()
print(mean_val)

[98 30 52  8 41 66 23 49 85 22 71 66 15 63 91 93 55 67 81 77 77 57 47  6
  1 20 24 71 59 89]
53.46666666666667


Normalize a 5x5 random matrix.


In [47]:
matrix=np.array(np.random.randint(0,10,(5,5)))
matrix
#used a min-max normalization method
matrix_normalized = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))
print(matrix_normalized)

[[0.55555556 0.77777778 0.88888889 0.66666667 0.44444444]
 [0.22222222 0.66666667 0.         0.22222222 0.11111111]
 [0.88888889 0.33333333 0.11111111 0.22222222 1.        ]
 [0.22222222 0.88888889 0.88888889 0.77777778 0.11111111]
 [0.55555556 0.66666667 0.66666667 1.         0.22222222]]


Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).


In [62]:
m1=np.array(np.random.randint(1,11,(5,3)))
m1

m2=np.array(np.random.randint(3,8,(3,2)))
m2

product=m1@m2  # @ can be used to calculate the dot product of two matrices
print(product)
print()
product2=np.dot(m1,m2)  # or we can use the np.dot(A,B) method
print(product2)


[[131 106]
 [128 109]
 [ 59  45]
 [ 83  65]
 [118  94]]

[[131 106]
 [128 109]
 [ 59  45]
 [ 83  65]
 [118  94]]


Create two 3x3 matrices and compute their dot product.


In [75]:
a=np.array(np.arange(1,10).reshape(3,3))
b=np.array(np.random.randn(3,3))

dot_product=np.dot(a,b)
print(dot_product)

[[  1.89862819  -2.97601756  -5.77456343]
 [  4.01342507  -9.27029945 -12.98596545]
 [  6.12822195 -15.56458133 -20.19736746]]


Given a 4x4 matrix, find its transpose.


In [113]:
matr=np.array(np.linspace(1,100,16).reshape(4,4),dtype=int)
print("Original\n", matr)
trans=np.transpose(matr)
print('Transpose\n', trans)

Original
 [[  1   7  14  20]
 [ 27  34  40  47]
 [ 53  60  67  73]
 [ 80  86  93 100]]
[[  1  27  53  80]
 [  7  34  60  86]
 [ 14  40  67  93]
 [ 20  47  73 100]]
Transpose
 [[  1  27  53  80]
 [  7  34  60  86]
 [ 14  40  67  93]
 [ 20  47  73 100]]


Create a 3x3 matrix and calculate its determinant.


In [84]:
m=np.array([[1,2,3],[4,23,45],[234,32,3]])

determinant=np.linalg.det(m)
print(determinant)

3902.9999999999995


Create two matrices ( A ) (3x4) and ( B ) (4x3), and compute the matrix product ( A \cdot B ).


In [92]:
A=np.array(np.arange(1,13).reshape(3,4))
B=np.array(np.arange(-4,8).reshape(4,3))

mat_product=np.matmul(A,B)
print(mat_product)

[[ 20  30  40]
 [ 28  54  80]
 [ 36  78 120]]


Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.


In [98]:
a=np.array(np.random.randint(1,100,(3,3)))
vector=np.array([1,2,3])

product=a@vector
print(product)

[266 263 421]


Solve the linear system ( Ax = b ) where ( A ) is a 3x3 matrix, and ( b ) is a 3x1 column vector.


In [106]:
a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,5,(3,1))
#Ax=b
inv_a=np.linalg.inv(a)
#x=b*A^(-1)
x=np.dot(inv_a,b)
print(x)

#second way

x1=np.linalg.solve(a,b)
print(x1)

[[ 1.97647059]
 [ 0.54117647]
 [-1.36470588]]
[[ 1.97647059]
 [ 0.54117647]
 [-1.36470588]]


Given a 5x5 matrix, find the row-wise and column-wise sums.


In [110]:
matrix=np.random.randint(1,10,(5,5))
print(matrix)
row_wise=matrix.sum(axis=1)
print(row_wise)

col_wise=matrix.sum(axis=0)
print(col_wise)

[[4 2 1 3 3]
 [7 4 4 3 6]
 [6 6 7 8 5]
 [1 5 4 4 4]
 [7 5 1 9 1]]
[13 24 32 18 23]
[25 22 17 27 19]
