In [115]:
import numpy as np

Create a vector with values ranging from 10 to 49.

In [116]:
vector=np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Create a 3x3 matrix with values ranging from 0 to 8.


In [117]:
matrix=np.array(np.arange(0,9).reshape(3,3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3x3 identity matrix.


In [118]:
id_matrix=np.eye(3,3,dtype=int)
id_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Create a 3x3x3 array with random values.


In [119]:
arr=np.array(np.random.randn(3,3,3))
arr


array([[[ 0.94905008, -0.67497293,  0.79956355],
        [-1.20526775, -0.65549843, -2.30550831],
        [ 1.98937981, -0.38180766, -0.16286755]],

       [[ 0.20206766,  0.60133334,  1.09344304],
        [-0.85223286,  0.30924165,  0.76315639],
        [ 1.58892021, -1.06285196,  1.57503694]],

       [[ 0.59758185, -0.69557755,  1.05637458],
        [-0.86603228,  0.79847238, -0.18066052],
        [-1.72511328,  0.10265193, -0.73083846]]])

Create a 10x10 array with random values and find the minimum and maximum values.


In [120]:
arr1=np.array(np.random.randint(-50,100,(3,3)))
print(arr1)

max_arr=arr1.max()
print(max_arr)

min_arr=arr1.min()
print(min_arr)

[[-18 -45 -13]
 [ -4 -29  12]
 [ 67  30 -14]]
67
-45


Create a random vector of size 30 and find the mean value.


In [121]:
vector=np.random.randint(0,100,30)
print(vector)

mean_val=vector.mean()
print(mean_val)

[86 23 26 82 60  2 48 72 88 26 94 81 80 79 69 10 60 11 36 18 82 32 71 30
 60 76 15 48 27 89]
52.7


Normalize a 5x5 random matrix.


In [122]:
matrix=np.array(np.random.randint(0,10,(5,5)))
matrix
#used a min-max normalization method
matrix_normalized = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))
print(matrix_normalized)

[[1.         0.77777778 0.77777778 0.55555556 0.55555556]
 [0.55555556 0.         0.22222222 0.         0.        ]
 [0.44444444 0.66666667 0.55555556 0.77777778 0.22222222]
 [0.55555556 0.77777778 0.55555556 0.22222222 0.33333333]
 [0.11111111 0.33333333 0.66666667 1.         0.44444444]]


Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).


In [123]:
m1=np.array(np.random.randint(1,11,(5,3)))
m1

m2=np.array(np.random.randint(3,8,(3,2)))
m2

product=m1@m2  # @ can be used to calculate the dot product of two matrices
print(product)
print()
product2=np.dot(m1,m2)  # or we can use the np.dot(A,B) method
print(product2)


[[ 94  72]
 [ 77  62]
 [107  95]
 [ 94  89]
 [ 65  48]]

[[ 94  72]
 [ 77  62]
 [107  95]
 [ 94  89]
 [ 65  48]]


Create two 3x3 matrices and compute their dot product.


In [124]:
a=np.array(np.arange(1,10).reshape(3,3))
b=np.array(np.random.randn(3,3))

dot_product=np.dot(a,b)
print(dot_product)

[[-14.28953746  -3.85404136   2.68880765]
 [-31.39929391  -7.95873915   7.10036813]
 [-48.50905036 -12.06343694  11.51192862]]


Given a 4x4 matrix, find its transpose.


In [125]:
matr=np.array(np.linspace(1,100,16).reshape(4,4),dtype=int)
print("Original\n", matr)
trans=np.transpose(matr)
print('Transpose\n', trans)

Original
 [[  1   7  14  20]
 [ 27  34  40  47]
 [ 53  60  67  73]
 [ 80  86  93 100]]
Transpose
 [[  1  27  53  80]
 [  7  34  60  86]
 [ 14  40  67  93]
 [ 20  47  73 100]]


Create a 3x3 matrix and calculate its determinant.


In [126]:
m=np.array([[1,2,3],[4,23,45],[234,32,3]])

determinant=np.linalg.det(m)
print(determinant)

3902.9999999999995


Create two matrices ( A ) (3x4) and ( B ) (4x3), and compute the matrix product ( A \cdot B ).


In [127]:
A=np.array(np.arange(1,13).reshape(3,4))
B=np.array(np.arange(-4,8).reshape(4,3))

mat_product=np.matmul(A,B)
print(mat_product)

[[ 20  30  40]
 [ 28  54  80]
 [ 36  78 120]]


Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.


In [128]:
a=np.array(np.random.randint(1,100,(3,3)))
vector=np.array([1,2,3])

product=a@vector
print(product)

[463 166 264]


Solve the linear system ( Ax = b ) where ( A ) is a 3x3 matrix, and ( b ) is a 3x1 column vector.


In [129]:
a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,5,(3,1))
#Ax=b
inv_a=np.linalg.inv(a)
#x=b*A^(-1)
x=np.dot(inv_a,b)
print(x)

#second way

x1=np.linalg.solve(a,b)
print(x1)

[[ 0.86206897]
 [ 0.20689655]
 [-0.24137931]]
[[ 0.86206897]
 [ 0.20689655]
 [-0.24137931]]


Given a 5x5 matrix, find the row-wise and column-wise sums.


In [130]:
matrix=np.random.randint(1,10,(5,5))
print(matrix)
row_wise=matrix.sum(axis=1)
print(row_wise)

col_wise=matrix.sum(axis=0)
print(col_wise)

[[1 8 8 6 2]
 [7 7 3 4 7]
 [8 9 9 3 5]
 [1 1 7 8 7]
 [3 6 8 2 8]]
[25 28 34 24 27]
[20 31 35 23 29]
